CREATE DATABASE IF NOT EXISTS stu_sys DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
USE stu_sys;
CREATE TABLE IF NOT EXISTS grades (
    id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(20) NOT NULL COMMENT '年级/届数',
    CONSTRAINT pk_grade PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '年级表';
CREATE TABLE IF NOT EXISTS classes (
    id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(20) NOT NULL COMMENT '班级名',
    grade_id BIGINT COMMENT '年级ID',
    CONSTRAINT fk_grade_class FOREIGN KEY (grade_id) REFERENCES grade(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '班级表';
CREATE TABLE IF NOT EXISTS students (
    id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(20) NOT NULL COMMENT '姓名',
    number VARCHAR(20) COMMENT '学号',
    class_id BIGINT COMMENT '班级ID',
    CONSTRAINT pk_student PRIMARY KEY (id),
    CONSTRAINT fk_student_class FOREIGN KEY (id) REFERENCES class(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '学生表';
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(20) NOT NULL COMMENT '课程名',
    code VARCHAR(20) COMMENT '课程代码',
    CONSTRAINT pk_course PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '课程表';
CREATE TABLE IF NOT EXISTS scores (
    id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
    score INT COMMENT '成绩',
    course_id BIGINT COMMENT '课程ID',
    student_id BIGINT COMMENT '学生ID',
    team VARCHAR(20) COMMENT '学期',
    CONSTRAINT pk_scores PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '成绩表';
CREATE TABLE IF NOT EXISTS student_course (
    id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
    course_id BIGINT COMMENT '课程ID',
    student_id BIGINT COMMENT '学生ID',
    team VARCHAR(20) COMMENT '学期',
    status ENUM('已选完', '已修完', '已退选') COMMENT '课程状态',
    CONSTRAINT pk_student_course PRIMARY KEY (id),
    CONSTRAINT fk_course FOREIGN KEY course(id),
    CONSTRAINT fk_stu_cour_course FOREIGN KEY (id) REFERENCES student(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT '学生_课程表';